app = "email-scheduler-ocaml"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

# Pass environment variables to the container
[env]
  BUCKET_NAME = "your-tigris-bucket-name"
  ORG_ID = "99"
  OCAMLLOG = "info"
  AWS_REGION = "auto"
  AWS_ENDPOINT_URL_S3 = "https://fly.storage.tigris.dev"

# For one-shot execution (no processes block needed)
# Python will use `flyctl machine run` to execute

# This is CRITICAL: Creates a persistent volume for the local DB copy
[mounts]
  source = "scheduler_data"
  destination = "/app/data"

# Resource limits for production workload
[[vm]]
  memory = "4gb"
  cpu_kind = "performance"
  cpus = 4

# Allow FUSE for TigrisFS mounting
[mounts]
  processes = ["app"] 