app = "email-scheduler"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  OCAML_VERSION = "5.1.0"

# For one-shot execution (no processes block needed)
# Python will use `flyctl machine run` to execute

[mounts]
  source = "scheduler_data"
  destination = "/app/data"

# Resource limits
[[vm]]
  memory = "4gb"
  cpu_kind = "performance"
  cpus = 4 